### ISSUE TITLE
Handle the version attribute setup in a more intelligent fashion

### ISSUE THREAD

**Issue by tas50** [chef-cookbooks/squid#50]
Having to hard code a version of squid based on the distro version is not a sustainable setup.  We need to discover it post install

**Comment by DavidJFelix** [comment]
👍 It's pretty bad how it currently is. Right now it's defaulting to 3.1 and only has Ubuntu specified for up to 14.10, so it's missing 3 releases.

The Debian version doesn't seem to gracefully handle 'testing' or 'sid'

### Ubuntu:

15.04 -> 3.3
15.10 -> 3.3
16.04 -> 3.5

**Comment by tas50** [comment]
Closing this out since the logic behind this has been reworked. We have a helper now for some of this which we can use to add logic if necessary.
