### ISSUE TITLE
Add include for additional .conf files inside squid.conf.erb template

### ISSUE THREAD

**Issue by mkristan** [chef-cookbooks/squid#61]
### Cookbook version

1.1.1
### Chef-client version

12.5.1
### Platform Details

CentOS
### Scenario:

I would like to write a wrapper cookbook that adds additional squid configurations but do so in a way that doesn't require overwriting the squid cookbook's squid.conf.erb template.  I'd rather create a conf.d directory and put additional configurations in that directory.  An existing pull request from 2015 appears to solve that problem.
### Steps to Reproduce:

I'm using the fork of the chef-cookbooks/squid and merged in the changes from pull request 42 into master on my local repository.
### Expected Result:

The updated squid.conf.erb template contains an 'include' statement allowing me to add additional rules in those directories.

**Comment by tas50** [comment]
Fixed and released
