### ISSUE TITLE
Allowing private ip addresses to use the squid proxy

### ISSUE THREAD

**Issue by kkniggatt** [chef-cookbooks/squid#71]
### Cookbook version
2.0

### Chef-client version
12.4.1

### Platform Details
CentOS 6.7 x86_64

### The Problem
I only want to allow RFC1918 ip addresses to use the squid proxy.

As [squid.conf.erb](https://github.com/chef-cookbooks/squid/blob/master/templates/default/squid.conf.erb#L23-L27) already has private ip addresses assigned to the localnet ACL, it seems that [node\['squid'\]\['localnets'\]](https://github.com/chef-cookbooks/squid/blob/master/attributes/default.rb#L40) should be left empty.  But, if it is left empty, [a rule is never created to allow localnet to use the proxy](https://github.com/chef-cookbooks/squid/blob/master/templates/default/squid.conf.erb#L56).  On the other hand, if node['squid']['localnets'] is left as-is, squid is not very happy.

```
2016/11/15 09:01:30| WARNING: (B) '10.0.0.0/8' is a subnetwork of (A) '10.0.0.0/8'
2016/11/15 09:01:30| WARNING: because of this '10.0.0.0/8' is ignored to keep splay tree searching predictable
2016/11/15 09:01:30| WARNING: You should probably remove '10.0.0.0/8' from the ACL named 'localnet'
2016/11/15 09:01:30| WARNING: (B) '172.16.0.0/12' is a subnetwork of (A) '172.16.0.0/12'
2016/11/15 09:01:30| WARNING: because of this '172.16.0.0/12' is ignored to keep splay tree searching predictable
2016/11/15 09:01:30| WARNING: You should probably remove '172.16.0.0/12' from the ACL named 'localnet'
2016/11/15 09:01:30| WARNING: (B) '172.16.0.0/12' is a subnetwork of (A) '172.16.0.0/12'
2016/11/15 09:01:30| WARNING: because of this '172.16.0.0/12' is ignored to keep splay tree searching predictable
2016/11/15 09:01:30| WARNING: You should probably remove '172.16.0.0/12' from the ACL named 'localnet'
2016/11/15 09:01:30| WARNING: (B) '192.168.0.0/16' is a subnetwork of (A) '192.168.0.0/16'
2016/11/15 09:01:30| WARNING: because of this '192.168.0.0/16' is ignored to keep splay tree searching predictable
2016/11/15 09:01:30| WARNING: You should probably remove '192.168.0.0/16' from the ACL named 'localnet'
2016/11/15 09:01:30| WARNING: (B) '192.168.0.0/16' is a subnetwork of (A) '192.168.0.0/16'
2016/11/15 09:01:30| WARNING: because of this '192.168.0.0/16' is ignored to keep splay tree searching predictable
2016/11/15 09:01:30| WARNING: You should probably remove '192.168.0.0/16' from the ACL named 'localnet'
```

Perhaps [the static ACL entries](https://github.com/chef-cookbooks/squid/blob/master/templates/default/squid.conf.erb#L23-L27) should be removed.

**Comment by nlopes** [comment]
I'd love to see this fixed. I think removing the static entries is the way to go here.
