### ISSUE TITLE
Ubuntu installs `squid3` package and configuration in `squid` directories

### ISSUE THREAD

**Issue by dustyburwell** [chef-cookbooks/squid#72]
### Cookbook version
3.0.0

### Platform Details
Ubuntu 16.04, AWS

When installing Squid using this chef cookbook on Ubuntu 16.04, the recipe installs config to the wrong location. This cookbook assumes the name of the package, and paths to all relavent directories, is "squid3". For this version of Ubuntu, `squid3` appears to be a valid package, as is `squid`, but the service is installed as `squid` and config and log directories are `squid`.

I've worked around this by overriding all of the relevant node attributes to point the right directories.

e.g.

```ruby
node.override['squid']['package'] = 'squid'
node.override['squid']['config_dir'] = '/etc/squid'
node.override['squid']['config_file'] = '/etc/squid/squid.conf'
node.override['squid']['service_name'] = 'squid'
node.override['squid']['log_dir'] = '/var/log/squid'
node.override['squid']['cache_dir'] = '/var/spool/squid'
node.override['squid']['coredump_dir'] = '/var/spool/squid'
```

**Comment by kylegoch** [comment]
Seeing this as well. When running in test kitchen I get the following on Ubuntu 16.04:
```
  * service[squid3] action enable
    
    ================================================================================
    Error executing action `enable` on resource 'service[squid3]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /bin/systemctl --system enable squid3 ----
    STDOUT: 
    STDERR: Failed to execute operation: No such file or directory
    ---- End output of /bin/systemctl --system enable squid3 ----
    Ran /bin/systemctl --system enable squid3 returned 1
    
    Resource Declaration:
    ---------------------
    # In /opt/kitchen/cache/cookbooks/squid/recipes/default.rb
    
    100: service node['squid']['service_name'] do
    101:   supports restart: true, status: true, reload: true
    102:   action [:enable, :start]
    103:   retries 5
    104: end
    
    Compiled Resource:
    ------------------
    # Declared in /opt/kitchen/cache/cookbooks/squid/recipes/default.rb:100:in `from_file'
    
    service("squid3") do
      action [:enable, :start]
      supports {:restart=>true, :status=>true, :reload=>true}
      retries 5
      retry_delay 2
      default_guard_interpreter :default
      service_name "squid3"
      pattern "squid3"
      declared_type :service
      cookbook_name "squid"
      recipe_name "default"
    end
    
    Platform:
    ---------
    x86_64-linux
    
  * service[squid3] action reload (up to date)
```

However, adding the override attributes @dustyburwell added resolved the issue.

**Comment by andibaer** [comment]
perhaps it´s possible to use something like this?

case node['platform_family']

when 'debian'
  if node['platform_version'].to_i == 16
    default['squid']['package'] = 'squid'
    default['squid']['config_dir'] = '/etc/squid'
    default['squid']['config_file'] = '/etc/squid/squid.conf'
    default['squid']['log_dir'] = '/var/log/squid'
    default['squid']['cache_dir'] = '/var/spool/squid'
    default['squid']['coredump_dir'] = '/var/spool/squid'
  else
    default['squid']['package'] = 'squid3'
    default['squid']['config_dir'] = '/etc/squid3'
    default['squid']['config_file'] = '/etc/squid3/squid.conf'
    default['squid']['log_dir'] = '/var/log/squid3'
    default['squid']['cache_dir'] = '/var/spool/squid3'
    default['squid']['coredump_dir'] = '/var/spool/squid3'
  end

when 'smartos'
  default['squid']['listen_interface'] = 'net0'

when 'freebsd'
  default['squid']['config_dir'] = '/usr/local/etc/squid'
  default['squid']['config_file'] = '/usr/local/etc/squid/squid.conf'
  default['squid']['cache_dir'] = '/var/squid/cache'
  default['squid']['coredump_dir'] = '/var/squid/cache'
end

**Comment by ericxnelson** [comment]
Got me too! Thanks for the temp fix @andibaer

**Comment by tas50** [comment]
I’m adding the Type: Jump In GitHub label to this issue. This is a great issue for someone to get their feet wet with and we’d love a PR to resolves the issue.
