### ISSUE TITLE
/libraries folder is currently missing in your 'master' branch  

### ISSUE THREAD

**Issue by klutarevich** [chef-cookbooks/squid#74]
### Cookbook version
3.1.0

### Chef-client version
12.9

### Platform Details
Ubuntu 14.04

### Steps to Reproduce:
include recipe[squid] in your runlist

### Expected Result:
cookbook [squid] runs successfully

### Actual Result:
 NameError
  ---------
  uninitialized constant Opscode::Squid

**Comment by tas50** [comment]
This has been fixed on master. Sorry about that
